// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjwKlb5YQpxLdX3haAb9Ed_QoJqYWEGA8',
    appId: '1:299269538562:android:b8b7c1b4d587729724381b',
    messagingSenderId: '299269538562',
    projectId: 'app-dat-xe-38f38',
    databaseURL: 'https://app-dat-xe-38f38-default-rtdb.firebaseio.com',
    storageBucket: 'app-dat-xe-38f38.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtXrr4EycZZVdzzK6XqsO-WKSTP5zUuAA',
    appId: '1:299269538562:ios:cd7fca81dd45805924381b',
    messagingSenderId: '299269538562',
    projectId: 'app-dat-xe-38f38',
    databaseURL: 'https://app-dat-xe-38f38-default-rtdb.firebaseio.com',
    storageBucket: 'app-dat-xe-38f38.appspot.com',
    iosBundleId: 'com.example.driversApp.RunnerTests',
  );
}
